//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlanyaMedicalHelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public string Note { get; set; }
        public string Descriptions { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<bool> PaymentStatus { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<int> PriceType { get; set; }
        public Nullable<bool> AppointmentStatus { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
