//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlanyaMedicalHelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyPayment
    {
        public int Id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Type { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> Visible { get; set; }
        public string PaymentNo { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
