//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlanyaMedicalHelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public Nullable<int> MusteriId { get; set; }
        public Nullable<int> AppointmentId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> Visible { get; set; }
        public string Description { get; set; }
        public Nullable<bool> PaymentStatus { get; set; }
        public Nullable<int> PriceType { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
