//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlanyaMedicalHelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockCount
    {
        public int Id { get; set; }
        public Nullable<int> StockId { get; set; }
        public Nullable<int> Count { get; set; }
        public string Description { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool Visible { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
